from Deque_DIY import Deque_DIY
from Stack_DIY import Stack_DIY
from Queue_DIY import Queue_DIY

def main():
    st1 = Stack_DIY()
    qu1 = Queue_DIY()
    deq1 = Deque_DIY()
    
    #arr = [1,2,2,3,4,5,6]
    print("----stack test ----------")
    st1.push(10)
    st1.push(20)
    st1.push(30)
    st1.push(40)
    print(st1)
    print(st1.peek())
    st1.pop()
    st1.pop()
    print(st1.peek())
    print(st1)
    print("----queue test ----------")
    qu1.append(10)
    qu1.append(20)
    qu1.append(30)
    qu1.append(40)
    qu1.append(50)
    qu1.append(60)
    qu1.append(70)
    qu1.append(80)
    print(qu1)
    qu1.pop()
    qu1.pop()
    qu1.pop()
    print(qu1.peek())
    print(qu1)
    
    print("----deque test ----------")  
    deq1.append(10)
    deq1.append(20)
    deq1.append(30)
    deq1.append(40)
    deq1.append(50)
    deq1.append(60)
    deq1.append(70)
    deq1.append(80)
    deq1.appendleft(-90)
    deq1.appendleft(-100)
    print(deq1)
    deq1.pop()
    deq1.pop()
    deq1.pop()
    deq1.pop()
    print(deq1)
    deq1.popleft()
    deq1.popleft()
    deq1.popleft()
    deq1.popleft()
    print(deq1.peek())
    print(deq1.peekleft())
    print(deq1)
    
    
    
main()